Move driver includes to bottom and add macro
- driver includes moved to address compile time errors with undefined reference to GPIO_RegDef_t
- macro to convert PGIO base address to portcode